USE master
IF DB_ID(N'KutinMusic') IS NOT NULL
DROP DATABASE KutinMusic;

ALTER DATABASE [KutinMusic] SET SINGLE_USER WITH ROLLBACK IMMEDIATE

CREATE DATABASE KutinMusic
ALTER AUTHORIZATION ON DATABASE::KutinMusic TO [sa]