USE [master]
GO
CREATE LOGIN [employee01] WITH PASSWORD=N'VerySTRPass1' MUST_CHANGE,
DEFAULT_DATABASE=[MedExamSys], CHECK_EXPIRATION=ON,CHECK_POLICY=ON

CREATE LOGIN [employee02] WITH PASSWORD=N'VerySTRPass2' MUST_CHANGE,
DEFAULT_DATABASE=[MedExamSys], CHECK_EXPIRATION=ON,CHECK_POLICY=ON

CREATE LOGIN [employee03] WITH PASSWORD=N'VerySTRPass3' MUST_CHANGE,
DEFAULT_DATABASE=[MedExamSys], CHECK_EXPIRATION=ON,CHECK_POLICY=ON

CREATE LOGIN [employee04] WITH PASSWORD=N'VerySTRPass4' MUST_CHANGE,
DEFAULT_DATABASE=[MedExamSys], CHECK_EXPIRATION=ON,CHECK_POLICY=ON

CREATE LOGIN [employee05] WITH PASSWORD=N'VerySTRPass5' MUST_CHANGE,
DEFAULT_DATABASE=[MedExamSys], CHECK_EXPIRATION=ON,CHECK_POLICY=ON

CREATE LOGIN [employee06] WITH PASSWORD=N'VerySTRPass6' MUST_CHANGE,
DEFAULT_DATABASE=[MedExamSys], CHECK_EXPIRATION=ON,CHECK_POLICY=ON

CREATE LOGIN [employee07] WITH PASSWORD=N'VerySTRPass7' MUST_CHANGE,
DEFAULT_DATABASE=[MedExamSys], CHECK_EXPIRATION=ON,CHECK_POLICY=ON

CREATE LOGIN [employee08] WITH PASSWORD=N'VerySTRPass8' MUST_CHANGE,
DEFAULT_DATABASE=[MedExamSys], CHECK_EXPIRATION=ON,CHECK_POLICY=ON

CREATE LOGIN [employee09] WITH PASSWORD=N'VerySTRPass9' MUST_CHANGE,
DEFAULT_DATABASE=[MedExamSys], CHECK_EXPIRATION=ON,CHECK_POLICY=ON